DOMAIN = "energyhub"
DEFAULT_SCAN_INTERVAL = 30  # seconds
MIN_SCAN_INTERVAL = 5
MAX_SCAN_INTERVAL = 300
CONF_PAIRING_CODE = "pairing_code"
CONF_API_URL = "api_url"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_SELECTED_ENTITIES = "selected_entities"
CONF_GRID_POWER = "grid_power_entity"        # Netzbezug/Einspeisung (W)
CONF_PV_POWER = "pv_power_entity"            # PV Produktion (W)
CONF_BATTERY_POWER = "battery_power_entity"  # Batterie Leistung (W)
CONF_BATTERY_SOC = "battery_soc_entity"      # Batterie Ladestand (%)
CONF_SWITCHES = "switch_entities"            # Schalter zum Freigeben
CONF_INVERT_GRID = "invert_grid"             # Vorzeichen Netzbezug umkehren
DEFAULT_API_URL = "https://eeg.svr.dev/api"
